// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions 
{
  static FirebaseOptions get currentPlatform 
  {
    if (kIsWeb) {return web;}
    switch (defaultTargetPlatform) 
    {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbk8NXv1RJk8gXsT4-wTTjMzwJqXUvR4A',
    appId: '1:333803948536:web:86622a108d4bc7fa712e0d',
    messagingSenderId: '333803948536',
    projectId: 'tp-modul-database',
    authDomain: 'tp-modul-database.firebaseapp.com',
    storageBucket: 'tp-modul-database.firebasestorage.app',
    measurementId: 'G-LKC7X3H6CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYwMcIhKVRJuokF4I6UEZ1Cdzo92j20w',
    appId: '1:333803948536:android:2d7f9dd27ee5ff63712e0d',
    messagingSenderId: '333803948536',
    projectId: 'tp-modul-database',
    storageBucket: 'tp-modul-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa14fuYlBj-GBNUdcwaOLf03hcQnyuRx4',
    appId: '1:333803948536:ios:d29ac08f6df98159712e0d',
    messagingSenderId: '333803948536',
    projectId: 'tp-modul-database',
    storageBucket: 'tp-modul-database.firebasestorage.app',
    iosBundleId: 'com.example.tpmod13',
  );
}